# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: response.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\x12\noral.im.v1\"\x8d\x01\n\x08Response\x12\x0b\n\x03\x63md\x18\x01 \x01(\x05\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x03\x12\x12\n\nerror_desc\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x12\n\ninbox_type\x18\x05 \x01(\x03\x12&\n\x04\x62ody\x18\x06 \x01(\x0b\x32\x18.oral.im.v1.ResponseBody\"\xf7\x01\n\x0cResponseBody\x12;\n\x12new_message_notify\x18\xf4\x03 \x01(\x0b\x32\x1c.oral.im.v1.NewMessageNotifyH\x00\x12H\n\x1b\x63reate_conversation_v2_body\x18\xe1\x04 \x01(\x0b\x32 .oral.im.v1.ConversationInfoListH\x00\x12X\n+get_conversation_info_list_v2_response_body\x18\xe2\x04 \x01(\x0b\x32 .oral.im.v1.ConversationInfoListH\x00\x42\x06\n\x04\x62ody\"\x85\x01\n\x10NewMessageNotify\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x19\n\x11\x63onversation_type\x18\x03 \x01(\x05\x12\x13\n\x0bnotify_type\x18\x04 \x01(\x05\x12(\n\x07message\x18\x05 \x01(\x0b\x32\x17.oral.im.v1.MessageBody\"\xd1\x01\n\x0bMessageBody\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x19\n\x11\x63onversation_type\x18\x02 \x01(\x05\x12\x19\n\x11server_message_id\x18\x03 \x01(\x03\x12\x1d\n\x15index_in_conversation\x18\x04 \x01(\x03\x12\x1d\n\x15\x63onversation_short_id\x18\x05 \x01(\x03\x12\x14\n\x0cmessage_type\x18\x06 \x01(\x05\x12\x0e\n\x06sender\x18\x07 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\"T\n\x14\x43onversationInfoList\x12<\n\x16\x63onversation_info_list\x18\x01 \x03(\x0b\x32\x1c.oral.im.v1.ConversationInfo\"u\n\x10\x43onversationInfo\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x1d\n\x15\x63onversation_short_id\x18\x02 \x01(\x03\x12\x19\n\x11\x63onversation_type\x18\x03 \x01(\x05\x12\x0e\n\x06ticket\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE']._serialized_start=31
  _globals['_RESPONSE']._serialized_end=172
  _globals['_RESPONSEBODY']._serialized_start=175
  _globals['_RESPONSEBODY']._serialized_end=422
  _globals['_NEWMESSAGENOTIFY']._serialized_start=425
  _globals['_NEWMESSAGENOTIFY']._serialized_end=558
  _globals['_MESSAGEBODY']._serialized_start=561
  _globals['_MESSAGEBODY']._serialized_end=770
  _globals['_CONVERSATIONINFOLIST']._serialized_start=772
  _globals['_CONVERSATIONINFOLIST']._serialized_end=856
  _globals['_CONVERSATIONINFO']._serialized_start=858
  _globals['_CONVERSATIONINFO']._serialized_end=975
# @@protoc_insertion_point(module_scope)
