"""baseline

Revision ID: 0aa46ef26514
Revises:
Create Date: 2026-07-19 15:54:12.537690

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0aa46ef26514"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatars",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_avatar_id", sa.String(length=64), nullable=False),
        sa.Column("style", sa.String(length=32), nullable=False),
        sa.Column("cover_key", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("avatars", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_avatars_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "personas",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("tone", sa.String(length=128), nullable=False),
        sa.Column("values", sa.Text(), nullable=False),
        sa.Column("taboo_words", sa.Text(), nullable=False),
        sa.Column("avatar_char", sa.String(length=4), nullable=False),
        sa.Column("avatar_grad", sa.String(length=64), nullable=False),
        sa.Column("voice_id", sa.String(length=64), nullable=True),
        sa.Column("avatar_id", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_personas_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pipeline_tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("ip_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("script_text", sa.Text(), nullable=False),
        sa.Column("voice_id", sa.String(length=64), nullable=False),
        sa.Column("avatar_id", sa.String(length=64), nullable=False),
        sa.Column("platforms_json", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_step", sa.String(length=16), nullable=False),
        sa.Column("steps_json", sa.Text(), nullable=False),
        sa.Column("artifacts_json", sa.Text(), nullable=False),
        sa.Column("compute", sa.String(length=8), nullable=False),
        sa.Column("quota_cost", sa.Float(), nullable=False),
        sa.Column("randomize", sa.Boolean(), nullable=False),
        sa.Column("batch_id", sa.String(length=32), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("publish_at", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_tasks_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pipeline_tasks_ip_id"), ["ip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pipeline_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_pipeline_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "publish_accounts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("session_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publish_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_publish_accounts_platform"), ["platform"], unique=False)
        batch_op.create_index(batch_op.f("ix_publish_accounts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "publish_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("topics_json", sa.String(length=256), nullable=False),
        sa.Column("video_key", sa.String(length=256), nullable=False),
        sa.Column("cover_key", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("post_id", sa.String(length=64), nullable=False),
        sa.Column("retry_count", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publish_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_publish_jobs_platform"), ["platform"], unique=False)
        batch_op.create_index(batch_op.f("ix_publish_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_publish_jobs_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_publish_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "quota_accounts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("total_granted", sa.Float(), nullable=False),
        sa.Column("used_this_month", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quota_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quota_accounts_user_id"), ["user_id"], unique=True)

    op.create_table(
        "quota_price",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("step", sa.String(length=16), nullable=False),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step", "resolution", name="uq_step_res"),
    )
    op.create_table(
        "quota_usage",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("step", sa.String(length=16), nullable=False),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("compute", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quota_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quota_usage_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quota_usage_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quota_usage_user_id"), ["user_id"], unique=False)

    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("refresh_jti", sa.String(length=64), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_jti"),
    )
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_sessions_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_refresh_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "scripts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("persona_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("rewritten_text", sa.Text(), nullable=False),
        sa.Column("words_json", sa.Text(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scripts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scripts_persona_id"), ["persona_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scripts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("avatar_char", sa.String(length=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)

    op.create_table(
        "voices",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_voice_id", sa.String(length=64), nullable=False),
        sa.Column("gender", sa.String(length=16), nullable=False),
        sa.Column("emotion", sa.String(length=32), nullable=False),
        sa.Column("sample_key", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("voices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voices_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("voices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voices_user_id"))

    op.drop_table("voices")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))

    op.drop_table("users")
    with op.batch_alter_table("scripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scripts_user_id"))
        batch_op.drop_index(batch_op.f("ix_scripts_persona_id"))

    op.drop_table("scripts")
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_device_id"))

    op.drop_table("refresh_sessions")
    with op.batch_alter_table("quota_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quota_usage_user_id"))
        batch_op.drop_index(batch_op.f("ix_quota_usage_trace_id"))
        batch_op.drop_index(batch_op.f("ix_quota_usage_task_id"))

    op.drop_table("quota_usage")
    op.drop_table("quota_price")
    with op.batch_alter_table("quota_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quota_accounts_user_id"))

    op.drop_table("quota_accounts")
    with op.batch_alter_table("publish_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publish_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_publish_jobs_task_id"))
        batch_op.drop_index(batch_op.f("ix_publish_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_publish_jobs_platform"))

    op.drop_table("publish_jobs")
    with op.batch_alter_table("publish_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publish_accounts_user_id"))
        batch_op.drop_index(batch_op.f("ix_publish_accounts_platform"))

    op.drop_table("publish_accounts")
    with op.batch_alter_table("pipeline_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_pipeline_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_pipeline_tasks_ip_id"))
        batch_op.drop_index(batch_op.f("ix_pipeline_tasks_batch_id"))

    op.drop_table("pipeline_tasks")
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personas_user_id"))

    op.drop_table("personas")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("avatars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_avatars_user_id"))

    op.drop_table("avatars")
    # ### end Alembic commands ###
