"""add_im_tables

Revision ID: 0e66a46b4b38
Revises: c9d0e1f2a3b4
Create Date: 2026-07-20 08:51:01.397972

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e66a46b4b38'
down_revision: str | None = 'c9d0e1f2a3b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_im_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_im_messages_user_id'))

    op.drop_table('im_messages')
    with op.batch_alter_table('im_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_im_conversations_account_id'))
        batch_op.drop_index(batch_op.f('ix_im_conversations_user_id'))

    op.drop_table('im_conversations')
    op.drop_table('provider_config')
    with op.batch_alter_table('im_auto_reply_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_im_auto_reply_rules_user_id'))

    op.drop_table('im_auto_reply_rules')
    with op.batch_alter_table('im_listener_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_im_listener_states_account_id'))
        batch_op.drop_index(batch_op.f('ix_im_listener_states_user_id'))

    op.drop_table('im_listener_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_listener_states',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('last_heartbeat', sa.DATETIME(), nullable=True),
    sa.Column('error_msg', sa.VARCHAR(length=256), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('im_listener_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_im_listener_states_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_im_listener_states_account_id'), ['account_id'], unique=1)

    op.create_table('im_auto_reply_rules',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('trigger_pattern', sa.VARCHAR(length=256), nullable=False),
    sa.Column('reply_mode', sa.VARCHAR(length=16), nullable=False),
    sa.Column('reply_template', sa.TEXT(), nullable=False),
    sa.Column('llm_prompt', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('daily_limit', sa.INTEGER(), nullable=False),
    sa.Column('delay_min', sa.INTEGER(), nullable=False),
    sa.Column('delay_max', sa.INTEGER(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('im_auto_reply_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_im_auto_reply_rules_user_id'), ['user_id'], unique=False)

    op.create_table('provider_config',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('im_conversations',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=16), nullable=False),
    sa.Column('remote_uid', sa.VARCHAR(length=64), nullable=False),
    sa.Column('remote_nickname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('remote_avatar', sa.VARCHAR(length=256), nullable=False),
    sa.Column('dy_conversation_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dy_conversation_short_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dy_ticket', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_message_at', sa.DATETIME(), nullable=False),
    sa.Column('unread_count', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('im_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_im_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_im_conversations_account_id'), ['account_id'], unique=False)

    op.create_table('im_messages',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=4), nullable=False),
    sa.Column('msg_type', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('auto_replied', sa.BOOLEAN(), nullable=False),
    sa.Column('reply_content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_im_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_im_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###
