"""add_im_tables

Revision ID: 3c9752a6f9eb
Revises: c9d0e1f2a3b4
Create Date: 2026-07-20 09:16:57.149067

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9752a6f9eb'
down_revision: str | None = 'c9d0e1f2a3b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.String(length=32), server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_im_messages_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_im_messages_rule_id'))
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ###
