"""avatar preview_key

Revision ID: fed35a9ee146
Revises: 0aa46ef26514
Create Date: 2026-07-19 17:57:01.600275

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed35a9ee146'
down_revision: str | None = '0aa46ef26514'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('preview_key')

    # ### end Alembic commands ###
